pipeline {
    agent any

    environment {
        IMAGE_NAME = 'imhrkr/batch-api'
        IMAGE_TAG  = "1.${BUILD_NUMBER}"
    }

    stages {

        stage('Clean up directory') {
            steps {
                script {
                    sh 'rm -rf ./* ./.git'
                }
            }
        }

        stage('Clone Repository') {
            steps {
                echo "Cloning Repository..."
                git branch: 'main', url: 'https://github.com/beyond-sw-camp/be12-fin-HRIM-IMHR-BE.git'
            }
        }

        stage('Check cloned files') {
            steps {
                sh 'ls -al'
            }
        }

        stage('Check gradle wrapper') {
            steps {
                sh 'ls -al batch-api/gradle/wrapper'
            }
        }

        stage('Build') {
            steps {
                dir('batch-api') {
                    sh 'chmod +x gradlew'
                    sh './gradlew clean build --refresh-dependencies -x test'
                }
            }
        }

        stage('Docker Build & Push') {
            steps {
                dir('batch-api') {
                    withCredentials([usernamePassword(credentialsId: 'IMHR_DOCKER_HUB', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                        sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ."
                        sh "echo \$DOCKER_PASSWORD | docker login -u \$DOCKER_USERNAME --password-stdin"
                        sh "docker push ${IMAGE_NAME}:${IMAGE_TAG}"
                    }
                }
            }
        }

        stage('Update YAML and Push to Git') {
            steps {
                script {
                    def newVersion = "${IMAGE_TAG}"

                    withCredentials([
                        usernamePassword(credentialsId: 'IUCH_GIT', usernameVariable: 'GITHUB_USERNAME', passwordVariable: 'GITHUB_PASSWORD'),
                        string(credentialsId: 'IMHR_GIT_URL', variable: 'GITHUB_URL')
                    ]) {
                        dir('batch-api') {
                            def files = [
                                "rankJob.yaml",
                                "scoreJob.yaml",
                                "memberJob.yaml"
                            ]

                            files.each { file ->
                                sh "sed -i 's/latest/${newVersion}/g' ${file}"
                            }

                            sh """
                              git add .
                              git commit -m "[Deploy] v1.${BUILD_NUMBER} 배포"
                              echo "after commit"
                              git remote set-url origin https://${GITHUB_USERNAME}:${GITHUB_PASSWORD}@${GITHUB_URL}
                              echo "after seturl"
                              git push origin deploy/argo/cd
                            """
                        }

                    }
                }
            }
        }
    }
}
